### ISSUE TITLE
Project update

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/saas-website#1]
![Screen Shot 2020-04-15 at 11 27 10 PM](https://user-images.githubusercontent.com/55094125/79362530-e7c91080-7f70-11ea-9d42-debe293f7006.png)

Hi, this is what I am working on so far. I finished the structure of my home page. Also, is it okay if I turn _Tour_ into _Features_?

@Muxlowc

**Comment by muxlowc** [comment]
@Sam-Le68 awesome, thanks!
