### ISSUE TITLE
How can I adjust images size?

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/saas-website#2]
so in my prototype, I have small images like this. But I do not know how to adjust it into the size I want. Is there anyway I can solve this? 

also, when I tried class _embed_ into the 1st banner, it stops the positioning that the text box disappears. 

![Screen Shot 2020-04-16 at 4 11 23 AM](https://user-images.githubusercontent.com/55094125/79391066-093ef200-7f9b-11ea-9e62-20172998954e.png)

@muxlowc 
@mackenzierose

**Comment by muxlowc** [comment]
@Sam-Le68 have you tried putting them inside of a grid?
Also, if you can't get your embeds to work properly, you can just use img-flex or something else. As long as you can problem solve the issue, you should be okay :)

(also, make sure that you html pages are named tour.html / index.html / sing-up.html - this will help with markbot)

**Comment by Sam-Le68** [comment]
![Screen Shot 2020-04-18 at 4 51 41 AM](https://user-images.githubusercontent.com/55094125/79616885-543e3e00-8130-11ea-8ef4-7ca10de41306.png)
![Screen Shot 2020-04-18 at 4 52 51 AM](https://user-images.githubusercontent.com/55094125/79616932-76d05700-8130-11ea-90a2-ab24b589fd60.png)


I have tried and it did not turn out the way I wanted. Also, my website does not display eps and png files

@muxlowc 
@mackenzierose

**Comment by muxlowc** [comment]
@Sam-Le68 

1) i'll try playing around on my end right now for a better solution (ill message back in a few), but right off the bat I can tell you that you cannot use .eps files on websites - you'll have to convert them to .svgs.
2) your png image doesn't have the "images/" in front of it, so the code doesn't know where to grab from

**Comment by muxlowc** [comment]
@Sam-Le68 

Ok. So, what you might need to do is to actually change your gridifier setting to have a grid of 6 columns. So rather than having two grids side by side, you can actually have 1 grid with 4 units (taking up 1/3, 1/6, 1/3, 1/6). Then you can add in the grid-stretch/unit-content-distribute/content-fill. I have started the code for you below just by tweaking it a bit, though you still will have to change a few things im sure! But make sure you go to gridifier and change your columns to 6, and re-copy/paste..

```
  <article>
    <div class="wrapper grid grid-stretch">
      <div class="unit-content-distribute island unit xs-1 s-1 m-1 l-1-3">
        <p class="content-fill">You can make family video call for free.</p>
        <a class="btn" href="#">Try it now</a>
      </div>
      <div class="unit unit-content-distribute xs-1 s-1 m-1 l-1-6">
        <img class="img-flex quarter-img content-fill" src="images/2.jpg" alt="">
      </div>

      <div class="unit-content-distribute island unit xs-1 s-1 m-1 l-1-3">
        <p class="content-fill">With only $7.99 per month, you can share your screen. Grandma loves to see family photos, doesn’t she?</p>
        <a class="btn" href="#">Buy it now</a>
      </div>
      <div class="unit xs-1 s-1 m-1 l-1-6">
        <img class="img-flex quarter-img unit-content-distribute" src="images/3.jpg" alt="">
      </div>
    </div>
  </article>
```

Let me know if you get it to work! :)

**Comment by muxlowc** [comment]
sorry, I also added in a class in your 38em media query:

.quarter-img {
  object-fit: cover;
}

this will crop those images nicely!

**Comment by Sam-Le68** [comment]
It works, thank you.
