### ISSUE TITLE
I have some problem with image sizing 

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/saas-website#3]
This is my first problem:
![Screen Shot 2020-04-19 at 5 29 55 PM](https://user-images.githubusercontent.com/55094125/79685512-94eaa400-8263-11ea-83c3-4d2867b4dee2.png)
I actually managed to get it in nicely but somehow it turned out like this, I used .embed 

This is my second one: 
![Screen Shot 2020-04-19 at 5 28 57 PM](https://user-images.githubusercontent.com/55094125/79685537-c1062500-8263-11ea-8072-204221a06a63.png)
I do not know why this image turned out like this even though I tried the same embed as the 2 cards bellow it. Also, the header with the nav looks weird, I did put grid and unit and sx-1.

This is my last one: 
![Screen Shot 2020-04-19 at 5 30 16 PM](https://user-images.githubusercontent.com/55094125/79685580-0296d000-8264-11ea-8444-b17bdee4c0cb.png)
In certain medium screen size, the 2 cards become like this and I do not know why

@muxlowc 
@mackenzierose

**Comment by muxlowc** [comment]
@Sam-Le68 

for the banner - for some reason you class of desktop was messing around with your grid. Is there a reason you have a different hero banner for mobile & desktop? Alternatively, you can use the class "unit-s-hidden" instead of xs-1/s-1 which seems to fix that issue.

```
  <article class="grid-stretch push wrapper banner grid grid-middle">
    <div class="border-pup island-2 text-center unit-content-distribute unit unit-s-hidden m-2-5 l-2-5">
      <p class="exa push-1-2 content-fill">DISTANCE CAN'T SEPARATE OUR FAMILY</p>
      <a class="content-shrink btn" href="#">Download Call Up</a>
    </div>
    <div class="unit  unit-s-hidden m-3-5 l-3-5 unit-content-distribute">
      <img class="img-flex quarter-img content-fill" src="images/1.jpg" alt="">
    </div>
  </article>
```

For your mobile one, you don't actually even need to use grids/units if its just taking up 100%, so I took those out, and added in a class of "w-1" (ie width 100%) to your div with the text. Also your embed size wasn't quite the best dimensions, so i tried 16by9 which seemed to be better?

```
<article class="mobile push wrapper banner">
    <div class="embed embed-16by9">
      <img class="embed-item" src="images/1.jpg" alt="">
    </div>
    <div class="border-pup island text-center unit w-1">
      <p class="exa push-1-2">DISTANCE CAN'T SEPARATE OUR FAMILY</p>
      <a class="btn" href="#">Download Call Up</a>
    </div>
  </article>
```

Sorry i hope this helps!

**Comment by Sam-Le68** [comment]
Well it did fix the problem of my mobile version, but not the desktop, there is no change to the desktop at all. 

@muxlowc 
@mackenzierose

**Comment by muxlowc** [comment]
@Sam-Le68 Is this not what you're looking for? The above code I send for the banner is working for me:

<img width="1437" alt="Screen Shot 2020-04-21 at 2 37 16 PM" src="https://user-images.githubusercontent.com/59422623/79901349-b8395e80-83dd-11ea-9597-90ec375d037c.png">

**Comment by Sam-Le68** [comment]
That is what I want for my code :"> alright let me re-check my code again. Thank you

**Comment by Sam-Le68** [comment]
Yes it is my .desktop class, I fixed it. Thank you for your help.
